// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
    name: "ChartDemo",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "ChartDemo",
            targets: ["ChartDemo"],
            bundleIdentifier: "yossibank-yahoo.co.jp.ChartDemo",
            teamIdentifier: "6WHPY5MQSB",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .coins),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(
            url: "https://github.com/SnapKit/SnapKit.git",
            from: "5.7.1"
        ),
        .package(
            url: "https://github.com/danielgindi/Charts.git",
            from: "5.1.0"
        )
    ],
    targets: [
        .executableTarget(
            name: "ChartDemo",
            dependencies: [
                .product(name: "SnapKit", package: "SnapKit"),
                .product(name: "DGCharts", package: "Charts")
            ],
            path: "Sources",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
